server:
  port: 80
  servlet:
    context-path: /message/
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/message_demo?allowMultiQueries=true&serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: true

mybatis:
  type-aliases-package: com.school.message.web.pojo
  mapper-locations: classpath:com/school/message/web/*/../*mapper/..*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
